### ISSUE TITLE
Collate code of your own

### ISSUE THREAD

**Issue by xpdavid** [CS2103JAN2017-F11-B1/main#28]
There is something I miss out in the tutorial. Please refer to http://www.comp.nus.edu.sg/~cs2103/AY1617S2/ handbook-> Extract your code for code quality grading for details.

Although code collate should be done in V0.4, you may start to claim code of your own when you develop your application.

Last but not least, remember to update your test cases. :)

**Comment by ntudy** [comment]
One question:
Can we delete all the other branches and tags created by the lecturer?

**Comment by xpdavid** [comment]
Feel free to do so. But you better not delete tag like `priority.high` etc, something specified in the handout as it counts for your project management mark. :)
