### ISSUE TITLE
Help should be shown when input format is incorrect

### ISSUE THREAD

**Issue by ntudy** [CS2103JAN2017-F11-B1/main#33]
Example:
add task star/12/12/12 12:12

The user used the wrong prefix for start time, but actually JOBS will regard the whole string as the name. So there is no help or error message to show correct input format

**Comment by chrishendra93** [comment]
I think instead of rejecting this input, we should provide some kind of warning message? Since it is rather constraining if we outright reject this tag, and it would be difficult to implement unless we add some extra specs like task name should have its own prefix or no white space in between

**Comment by ntudy** [comment]
But the wrong input will then be saved as one task. The user has to delete it later by himself. 
How about we use " " to describe the name?

**Comment by chrishendra93** [comment]
I'm not sure, I feel that using " " is a bit inconvenient. Maybe we can discuss more about this in person for v 0.4 since this is not really essential?

**Comment by chrishendra93** [comment]
Another workaround might be to separate the add process for floating task and task with deadlines. Maybe you should add a flag add float task_name
